/* eslint-disable */
// Generated by Wrangler by running `wrangler types --include-runtime=false` (hash: aa014976ca130e9327a40c65029ecae5)
interface __BaseEnv_Env {
	AUTH0_DOMAIN: "abbaspour.auth0.com";
	AUTH0_AUDIENCE: "https://agents-mcp-worker.abbaspour.workers.dev/";
	MCP_SERVER_URL: "https://agents-mcp-worker.abbaspour.workers.dev";
}
declare namespace Cloudflare {
	interface GlobalProps {
		mainModule: typeof import("./src/index");
	}
	interface Env extends __BaseEnv_Env {}
}
interface Env extends __BaseEnv_Env {}
type StringifyValues<EnvType extends Record<string, unknown>> = {
	[Binding in keyof EnvType]: EnvType[Binding] extends string ? EnvType[Binding] : string;
};
declare namespace NodeJS {
	interface ProcessEnv extends StringifyValues<Pick<Cloudflare.Env, "AUTH0_DOMAIN" | "AUTH0_AUDIENCE" | "MCP_SERVER_URL">> {}
}
